[pytest]
pythonpath = 
    dataset-pipelines/continual-relation-extraction/src
    experiments/continual-relation-baselines/src
    experiments
testpaths = 
    dataset-pipelines/continual-relation-extraction/tests
    experiments/tests
